//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wintogo.MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wintogo.MultiLanguage.ResourceLang", typeof(ResourceLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 VHD模式说明.TXT 的本地化字符串。
        /// </summary>
        public static string FileName_VHD_Dynamic {
            get {
                return ResourceManager.GetString("FileName_VHD_Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要将程序放入中文文件夹运行。 的本地化字符串。
        /// </summary>
        public static string IsChinaMsg {
            get {
                return ResourceManager.GetString("IsChinaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜像文件应用失败！ 的本地化字符串。
        /// </summary>
        public static string Msg_ApplyError {
            get {
                return ResourceManager.GetString("Msg_ApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引导文件写入出错！boot文件夹不存在！ 的本地化字符串。
        /// </summary>
        public static string Msg_BCDError {
            get {
                return ResourceManager.GetString("Msg_BCDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件写入出错！bootmgr不存在！\n请检查写入过程是否中断 的本地化字符串。
        /// </summary>
        public static string Msg_bootmgrError {
            get {
                return ResourceManager.GetString("Msg_bootmgrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 镜像文件选择错误！请选择install.wim！ 的本地化字符串。
        /// </summary>
        public static string Msg_chooseinstallwim {
            get {
                return ResourceManager.GetString("Msg_chooseinstallwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择可移动设备 的本地化字符串。
        /// </summary>
        public static string Msg_chooseud {
            get {
                return ResourceManager.GetString("Msg_chooseud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作将会清除移动磁盘所有分区的所有数据，确认？ 的本地化字符串。
        /// </summary>
        public static string Msg_ClearPartition {
            get {
                return ResourceManager.GetString("Msg_ClearPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作完成！ 的本地化字符串。
        /// </summary>
        public static string Msg_Complete {
            get {
                return ResourceManager.GetString("Msg_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认您所选择的 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmChoose {
            get {
                return ResourceManager.GetString("Msg_ConfirmChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序将会重启，确认继续？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmRestart {
            get {
                return ResourceManager.GetString("Msg_ConfirmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制文件中...大约需要10分钟~1小时，请耐心等待！ 的本地化字符串。
        /// </summary>
        public static string Msg_Copy {
            get {
                return ResourceManager.GetString("Msg_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序删除临时文件出错！可重启程序或重启电脑重试！\n 的本地化字符串。
        /// </summary>
        public static string Msg_DeleteTempError {
            get {
                return ResourceManager.GetString("Msg_DeleteTempError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘，容量 的本地化字符串。
        /// </summary>
        public static string Msg_Disk_Space {
            get {
                return ResourceManager.GetString("Msg_Disk_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优盘容量小于VHD设定大小，请修改设置！ 的本地化字符串。
        /// </summary>
        public static string Msg_DiskSpaceError {
            get {
                return ResourceManager.GetString("Msg_DiskSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可移动磁盘容量不足16G，继续写入可能会导致程序出错！您确定要继续吗？ 的本地化字符串。
        /// </summary>
        public static string Msg_DiskSpaceWarning {
            get {
                return ResourceManager.GetString("Msg_DiskSpaceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果您不清楚您在做什么，请立即停止操作！ 的本地化字符串。
        /// </summary>
        public static string Msg_DoWhat {
            get {
                return ResourceManager.GetString("Msg_DoWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误！ 的本地化字符串。
        /// </summary>
        public static string Msg_error {
            get {
                return ResourceManager.GetString("Msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此系统不支持ESD文件处理！ 的本地化字符串。
        /// </summary>
        public static string Msg_ESDError {
            get {
                return ResourceManager.GetString("Msg_ESDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        public static string Msg_Failure {
            get {
                return ResourceManager.GetString("Msg_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB 是将要写入的优盘或移动硬盘\n误格式化，后果自负！ 的本地化字符串。
        /// </summary>
        public static string Msg_FormatTip {
            get {
                return ResourceManager.GetString("Msg_FormatTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘将会被格式化，此操作将不可恢复，您确定要继续吗？\n由于写入时间较长，请您耐心等待！\n写入过程中弹出写入可能无效属于正常现象，选是即可。 的本地化字符串。
        /// </summary>
        public static string Msg_FormatWarning {
            get {
                return ResourceManager.GetString("Msg_FormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此类优盘使用传统模式可能无法启动，确认继续？ 的本地化字符串。
        /// </summary>
        public static string Msg_Legacywarning {
            get {
                return ResourceManager.GetString("Msg_Legacywarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘符V不能被占用！ 的本地化字符串。
        /// </summary>
        public static string Msg_LetterV {
            get {
                return ResourceManager.GetString("Msg_LetterV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NTFS文件流异常\n请放心，此错误不影响正常使用 的本地化字符串。
        /// </summary>
        public static string Msg_ntfsstream {
            get {
                return ResourceManager.GetString("Msg_ntfsstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NTFS分区UEFI支持 的本地化字符串。
        /// </summary>
        public static string Msg_NtfsUefiSupport {
            get {
                return ResourceManager.GetString("Msg_NtfsUefiSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此选项仅在非UEFI模式下有效！ 的本地化字符串。
        /// </summary>
        public static string Msg_OnlyNonUefi {
            get {
                return ResourceManager.GetString("Msg_OnlyNonUefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名错误 的本地化字符串。
        /// </summary>
        public static string Msg_RenameError {
            get {
                return ResourceManager.GetString("Msg_RenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您勾选了重新分区，优盘或移动硬盘上的所有文件将被删除！\n注意是整个磁盘，不是一个分区！ 的本地化字符串。
        /// </summary>
        public static string Msg_Repartition {
            get {
                return ResourceManager.GetString("Msg_Repartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示！ 的本地化字符串。
        /// </summary>
        public static string Msg_Tip {
            get {
                return ResourceManager.GetString("Msg_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择优盘根目录 的本地化字符串。
        /// </summary>
        public static string Msg_UDRoot {
            get {
                return ResourceManager.GetString("Msg_UDRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此优盘不支持UEFI模式\n只有 Fixed Disk格式支持\n详情请看论坛说明！ 的本地化字符串。
        /// </summary>
        public static string Msg_UefiError {
            get {
                return ResourceManager.GetString("Msg_UefiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您所选择的是UEFI模式，此模式将会格式化您的整个移动磁盘！\n注意是整个磁盘！！！\n程序将会删除所有优盘分区！ 的本地化字符串。
        /// </summary>
        public static string Msg_UefiFormatWarning {
            get {
                return ResourceManager.GetString("Msg_UefiFormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若无弹出窗口，则当前程序已是最新版本！ 的本地化字符串。
        /// </summary>
        public static string Msg_UpdateTip {
            get {
                return ResourceManager.GetString("Msg_UpdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VHD模式下BCDBOOT执行出错！ 的本地化字符串。
        /// </summary>
        public static string Msg_VHDBcdbootError {
            get {
                return ResourceManager.GetString("Msg_VHDBcdbootError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VHD文件创建出错！ 的本地化字符串。
        /// </summary>
        public static string Msg_VHDCreationError {
            get {
                return ResourceManager.GetString("Msg_VHDCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您创建的VHD为动态大小VHD，实际VHD容量： 的本地化字符串。
        /// </summary>
        public static string Msg_VHDDynamicSize {
            get {
                return ResourceManager.GetString("Msg_VHDDynamicSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在VHD系统启动后将自动扩充为实际容量。请您在优盘留有足够空间确保系统正常启动！ 的本地化字符串。
        /// </summary>
        public static string Msg_VHDDynamicSize2 {
            get {
                return ResourceManager.GetString("Msg_VHDDynamicSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告！ 的本地化字符串。
        /// </summary>
        public static string Msg_warning {
            get {
                return ResourceManager.GetString("Msg_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WIM文件信息获取失败\n将按WIN8系统安装 的本地化字符串。
        /// </summary>
        public static string Msg_wiminfoerror {
            get {
                return ResourceManager.GetString("Msg_wiminfoerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理WIN7 USB启动时出现问题 的本地化字符串。
        /// </summary>
        public static string Msg_win7usberror {
            get {
                return ResourceManager.GetString("Msg_win7usberror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在写入... 的本地化字符串。
        /// </summary>
        public static string Msg_WriteProcessing {
            get {
                return ResourceManager.GetString("Msg_WriteProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在写入，您确定要取消吗？ 的本地化字符串。
        /// </summary>
        public static string Msg_WritingAbort {
            get {
                return ResourceManager.GetString("Msg_WritingAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XP系统不支持此操作 的本地化字符串。
        /// </summary>
        public static string Msg_XPNotCOMP {
            get {
                return ResourceManager.GetString("Msg_XPNotCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XP系统不支持UEFI模式写入 的本地化字符串。
        /// </summary>
        public static string Msg_XPUefiError {
            get {
                return ResourceManager.GetString("Msg_XPUefiError", resourceCulture);
            }
        }
    }
}
